services:
  backend:
    build:
      context: .
      target: back
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .
      target: front
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
