# Configuration SonarQube Cloud
sonar.organization=weisgerberestelle
sonar.projectKey=WeisgerberEstelle_P7-FSJA

# Sources
sonar.sources=back/src/main,front/src
sonar.tests=back/src/test,front/src
sonar.test.inclusions=**/*.spec.ts,**/*Test.java,**/*Tests.java

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

# Backend - Java
sonar.java.binaries=back/build/classes
sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml

# Frontend - Angular / TypeScript
sonar.typescript.lcov.reportPaths=front/coverage/microcrm/lcov.info

# Encodage
sonar.sourceEncoding=UTF-8
